In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import datasets,metrics

In [2]:
iris=datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
x=iris.data
y=iris.target
print(x,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
df=pd.DataFrame(x,columns=iris.feature_names)
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


In [5]:
df["target"]=iris.target
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  

In [6]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [7]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [8]:
df.isnull()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                False             False              False             False   
1                False             False              False             False   
2                False             False              False             False   
3                False             False              False             False   
4                False             False              False             False   
..                 ...               ...                ...               ...   
145              False             False              False             False   
146              False             False              False             False   
147              False             False              False             False   
148              False             False              False             False   
149              False             False              False             False   

     target  
0     False  
1     False  
2     False  
3     False  
4     False  
..      ...  
145   False  
146   False  
147   False  
148   False  
149   False  

[150 rows x 5 columns]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
print(x_train, x_test, y_train, y_test)

[[4.7 3.2 1.6 0.2]
 [5.4 3.9 1.3 0.4]
 [5.7 2.8 4.1 1.3]
 [5.6 2.9 3.6 1.3]
 [4.8 3.4 1.9 0.2]
 [6.4 2.8 5.6 2.2]
 [5.1 3.8 1.5 0.3]
 [4.3 3.  1.1 0.1]
 [5.4 3.4 1.5 0.4]
 [6.1 2.8 4.7 1.2]
 [5.2 3.4 1.4 0.2]
 [4.9 3.6 1.4 0.1]
 [6.3 2.8 5.1 1.5]
 [6.2 3.4 5.4 2.3]
 [5.7 2.8 4.5 1.3]
 [6.5 3.  5.2 2. ]
 [5.1 3.7 1.5 0.4]
 [5.1 3.4 1.5 0.2]
 [5.4 3.  4.5 1.5]
 [4.9 3.  1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [6.3 2.5 5.  1.9]
 [5.8 2.8 5.1 2.4]
 [5.  3.  1.6 0.2]
 [6.7 3.3 5.7 2.1]
 [7.  3.2 4.7 1.4]
 [6.4 2.7 5.3 1.9]
 [5.4 3.9 1.7 0.4]
 [5.8 4.  1.2 0.2]
 [5.1 2.5 3.  1.1]
 [5.8 2.6 4.  1.2]
 [5.8 2.7 5.1 1.9]
 [5.5 2.4 3.8 1.1]
 [4.8 3.1 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [6.1 2.8 4.  1.3]
 [6.8 3.  5.5 2.1]
 [5.6 2.8 4.9 2. ]
 [6.3 3.3 6.  2.5]
 [7.7 3.  6.1 2.3]
 [5.  3.4 1.6 0.4]
 [5.7 2.6 3.5 1. ]
 [5.7 3.  4.2 1.2]
 [6.  2.7 5.1 1.6]
 [5.5 2.5 4.  1.3]
 [5.7 4.4 1.5 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [7.3 2.9 6.3 1.8]
 [5.2 2.7 3.9 1.4]
 [4.5 2.3 1.3 0.3]
 [6.2 2.2 4.

In [10]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)


# Supervised Learning

## Linear Regression

In [11]:
from sklearn import linear_model
lr=linear_model.LinearRegression()

In [12]:
lr.fit(x_train, y_train)

LinearRegression()

In [13]:
predlr=lr.predict(x_test)
print(predlr)

[ 0.95706819 -0.04777425  1.80987458  1.18785244  1.54122335 -0.02186829
  1.17919646  2.01701611  1.91530271  1.47569278  1.58728681  1.59527039
 -0.09273449  2.14153176  1.99145974  1.49678404  2.06895137  1.41154021
  1.1706338   1.30039363  1.36904457 -0.08617556  0.01654642 -0.12223371
  1.69919905 -0.06279103  1.192028    1.19598749  0.03355352  1.59733419]


In [14]:
print(lr.score(x,y))

0.9301772172879391


## Logistic Regression

In [15]:
from sklearn import linear_model
lor=linear_model.LogisticRegression()

In [16]:
lor.fit(x_train, y_train)

LogisticRegression()

In [17]:
predlor=lor.predict(x_test)
print(predlor)

[1 0 2 1 2 0 1 2 2 1 1 2 0 2 2 2 2 1 1 1 1 0 0 0 2 0 1 1 0 2]


In [18]:
acclor=metrics.accuracy_score(y_test,predlor)
print(acclor)

0.9


## Decision Trees

In [19]:
from sklearn import tree
dt=tree.DecisionTreeClassifier()

In [20]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [21]:
preddt=dt.predict(x_test)
print(preddt)

[1 0 2 1 1 0 1 2 2 1 2 2 0 2 2 2 2 1 1 1 1 0 0 0 2 0 1 1 0 2]


In [22]:
accdt=metrics.accuracy_score(y_test,preddt)
print(accdt)

0.9


## Random Forest

In [23]:
from sklearn import ensemble
rf=ensemble.RandomForestClassifier()

In [24]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [25]:
predrf=rf.predict(x_test)
print(predrf)

[1 0 2 1 2 0 1 2 2 1 1 2 0 2 2 2 2 1 1 1 1 0 0 0 2 0 1 1 0 2]


In [26]:
accrf=metrics.accuracy_score(y_test,predrf)
print(accrf)

0.9


## Naive Bayes

In [27]:
from sklearn import naive_bayes
nb=naive_bayes.GaussianNB()

In [28]:
nb.fit(x_train, y_train)

GaussianNB()

In [29]:
prednb=nb.predict(x_test)
print(prednb)

[1 0 2 1 2 0 1 2 2 1 1 2 0 2 2 2 2 1 1 1 1 0 0 0 2 0 1 1 0 2]


In [30]:
accnb=metrics.accuracy_score(y_test,prednb)
print(accnb)

0.9


## K-Nearest Neighbors

In [31]:
from sklearn import neighbors
knn=neighbors.KNeighborsClassifier()

In [32]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [33]:
predknn=knn.predict(x_test)
print(predknn)

[1 0 2 1 2 0 1 2 2 2 1 2 0 2 2 2 2 2 1 1 1 0 0 0 2 0 1 1 0 2]


In [34]:
accknn=metrics.accuracy_score(y_test, predknn)
print(accknn)

0.9
